### ISSUE TITLE
Teste pro vander

### ISSUE THREAD

**Issue by ktabriga** [jvander/dsc#1]

**Comment by robertopihc** [comment]
recebi :)

2016-04-18 22:03 GMT-03:00 Jhonatan W. G. Catabriga <
notifications@github.com>:

> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/jvander/dsc/issues/1

## 

Roberto Pereira
Departamento de Informática
Universidade Federal do Paraná (UFPR)

**Comment by AndreSanchezSilva** [comment]
Eu tb =)))

Atenciosamente,
André Silva

2016-04-19 10:51 GMT-03:00 robertopihc notifications@github.com:

**Comment by jvander** [comment]
Eu também recebi. Funciona.
André, vamos ajudar na versão 2.0 para agosto? Só alguns detalhes.

**Comment by AndreSanchezSilva** [comment]
Fala Jesus!!

Qual vai ser o desafio da 2.0?? To meio enrolado com a pós graduação, mas é
um sábado sim outro não, dá para eu dar uma mão.

Atenciosamente,
André Silva

Em 19 de abril de 2016 12:30, JVander notifications@github.com escreveu:

**Comment by jvander** [comment]
Grande André
Pois é, os desafios agora é dar um pouco de vida na interface, mostrando uns elementos gráficos de percepção, coisas que você gosta e eu também para deixar ela viva.

Ela está funcionando a todo vapor, já foi usado em disciplinas aqui em Campinas, em Curitiba, em Campo Mourão. Está lindo.. kkkk

Sabe que tudo isso é graças a seu esforço, do cata, do gardin... 

Terão uma homenagem na página inicial na V 2.
